### ISSUE TITLE
Step 5 in the readme is vague

### ISSUE THREAD

**Issue by Codeguyross** [FinalTwist/Ultima-Adventures#11]
Step 5. Download the drop-in additional files in the release tab, extract everything inside the Ultima-Adventures folder in the archive to your C:\Ultima-Adventures folder

Where is the 'release tab'?

**Comment by Jascen** [comment]
It's referring to this: https://github.com/FinalTwist/Ultima-Adventures/releases/tag/additionalfiles

I wouldn't bother with that, though. The 2.10 release split out server and client files. If you're running them on the same machine, just unzip both directly into C:\Ultima-Adventures
