### ISSUE TITLE
multi-language plan 

### ISSUE THREAD

**Issue by alucardxlx** [FinalTwist/Ultima-Adventures#12]
May I ask if there will be any future plans to design multi-language version switching? Or is it a plan to be able to translate to other languages through native cliloc files?

**Comment by Jascen** [comment]
There are no plans to translate UA. You will need to update the cliloc files as well as C# files (where a majority of the strings are).

Someone posted in the UA discord that they're translating to PT-BR. You can search "PT-BR" on discord to find the steps they used to programmatically translate
